[build]
pattern_script = """
<script type=\"module\">
import init from '{base}{js}';
init('{base}{wasm}').then( wasm => start_render_loop( wasm.render ) );
</script>
"""
target = "index.html"
dist = "dist"
